"""
Initialize application database.

Revision ID: c6b516e182b2
Revises: 
Create Date: 2024-07-31 18:06:42.500040
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6b516e182b2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_status",
        sa.Column("file_id", sa.String(), nullable=False),
        sa.Column("file_etags", sa.String(), nullable=False),
        sa.Column("added_by_user_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), default=sa.func.current_timestamp(), onupdate=sa.func.current_timestamp()),
        sa.Column("chrome_index_made", sa.Boolean(), nullable=False),
        sa.Column("process_status", sa.Boolean(), nullable=False)

    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_status")
    # ### end Alembic commands ###
